

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `LeslyJacobVideodb`.`Utilisateur` (idUtilisateur, nom) VALUES
(1, 'Alice Martin'),
(2, 'Bob Dupont'),
(3, 'Chloé Bernard'),
(4, 'David Moreau'),
(5, 'Emma Leroy'),
(6, 'François Dubois'),
(7, 'Gérome Petit'),
(8, 'Hélène Rousseau'),
(9, 'Isabelle Gauthier'),
(10, 'Julien Leroy'),
(11, 'Karine Fontaine'),
(12, 'Laurent Lefèvre'),
(13, 'Marie Dubois'),
(14, 'Nicolas Garnier'),
(15, 'Olivia Adam'),
(16, 'Paul Simon'),
(17, 'Quentin Lucas'),
(18, 'Roxane Moulin'),
(19, 'Sophie Roy'),
(20, 'Thomas Laurent'),
(21, 'Ursule Mercier'),
(22, 'Victor Perrin'),
(23, 'Wendy Lefebvre'),
(24, 'Xavier Roche'),
(25, 'Yasmine Bernard'),
(26, 'Zacharie Caron'),
(27, 'Amandine Faure'),
(28, 'Bastien Lambert'),
(29, 'Céline Hubert'),
(30, 'Dorian Valois'),
(31, 'Eloïse Lefebvre'),
(32, 'Florian Marchand'),
(33, 'Gwendoline Chevalier'),
(34, 'Henri Giraud'),
(35, 'Inès Bernard'),
(36, 'Jérôme Bourgeois'),
(37, 'Katia Dufour'),
(38, 'Léo Gérard'),
(39, 'Mélanie Picard'),
(40, 'Nathalie Delacour'),
(41, 'Olivier Noirot'),
(42, 'Patricia Dubois'),
(43, 'Quincy Richard'),
(44, 'Renée Dupuy'),
(45, 'Sébastien Chastel'),
(46, 'Tania Dubreuil'),
(47, 'Ugo Fontaine'),
(48, 'Valentin Roy'),
(49, 'Willy Lebrun'),
(50, 'Yvette Pichon'),
(51, 'Alexandre Fournier'),
(52, 'Béatrice Lefèvre'),
(53, 'Cédric Maillard'),
(54, 'Daisy Collin'),
(55, 'Édouard Larue'),
(56, 'Fanny Boivin'),
(57, 'Grégoire Morel'),
(58, 'Hugo Petit'),
(59, 'Irene Fleury'),
(60, 'Juliette Garcia'),
(61, 'Kévin Rousseau'),
(62, 'Lina Maheux'),
(63, 'Maxime Poirier'),
(64, 'Nora Gagnon'),
(65, 'Osmane Boulet'),
(66, 'Pascale Thibault'),
(67, 'Quentin Brun'),
(68, 'Romain Dumas'),
(69, 'Sabrina Robin'),
(70, 'Théo Boucher'),
(71, 'Ursuline Noel'),
(72, 'Victor Royer'),
(73, 'Warren Clément'),
(74, 'Xena Richard'),
(75, 'Yannick Truchot'),
(76, 'Zoe Lefèvre'),
(77, 'Alexis Petit'),
(78, 'Bénédicte Daniel'),
(79, 'Chantal Laville'),
(80, 'Dany Noël'),
(81, 'Émilie Chatelier'),
(82, 'Franck Huet'),
(83, 'Géraldine Luc'),
(84, 'Henriette Raymond'),
(85, 'Ignace Denis'),
(86, 'Julien Morel'),
(87, 'Karine Victor'),
(88, 'Lionel Caron'),
(89, 'Manon Charpentier'),
(90, 'Nicolas Léger'),
(91, 'Odile André'),
(92, 'Pierre Moreau'),
(93, 'Quintin Gaillard'),
(94, 'Rachid Diallo'),
(95, 'Sylvie Philippe'),
(96, 'Teddy Dumas'),
(97, 'Ursule Carpentier'),
(98, 'Victorien Fabre'),
(99, 'Wendy Dubois'),
(100, 'Xavier Marchand');


INSERT INTO `LeslyJacobVideodb`.`Video` (titre, description, miniature, fichier_video, date_publication, statut, auteur) VALUES
("Les Aventures d'Alice", 'Une aventure captivante dans un monde fantastique.', 'miniature1.jpg', 'video1.mp4', '2023-01-01', 'public', 1),
('Voyage au Centre de la Terre', 'Une exploration des profondeurs de notre planète.', 'miniature2.jpg', 'video2.mp4', '2023-01-02', 'public', 2),
('La Magie de Noël', "Un film sur l'esprit des fêtes.", 'miniature3.jpg', 'video3.mp4', '2023-01-03', 'public', 3),
('Un Monde Sous-Marin', "Découvrez les merveilles de l'océan.", 'miniature4.jpg', 'video4.mp4', '2023-01-04', 'public', 4),
('Secrets de la Nature', 'Un documentaire sur la biodiversité.', 'miniature5.jpg', 'video5.mp4', '2023-01-05', 'public', 5),
('Les Robots de Demain', 'Un aperçu des technologies futures.', 'miniature6.jpg', 'video6.mp4', '2023-01-06', 'public', 6),
('Histoire des Civilisations', 'Un voyage à travers le temps.', 'miniature7.jpg', 'video7.mp4', '2023-01-07', 'public', 7),
('La Cuisine Française', 'Recettes et astuces culinaires.', 'miniature8.jpg', 'video8.mp4', '2023-01-08', 'public', 8),
('Techniques de Peinture', 'Apprenez les bases de la peinture.', 'miniature9.jpg', 'video9.mp4', '2023-01-09', 'public', 9),
('Fitness à la Maison', 'Des exercices à faire chez soi.', 'miniature10.jpg', 'video10.mp4', '2023-01-10', 'public', 10),
('Voyage en Asie', 'Découvrez les cultures asiatiques.', 'miniature100.jpg', 'video100.mp4', '2023-04-10', 'public', 100);

